name: Auto-merge Crowdin PR

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  auto-merge:
    if: |
      github.actor == 'github-actions' &&
      startsWith(github.event.pull_request.title, 'New Crowdin translations')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Auto-merge PR
      if: github.actor == 'github-actions'
      uses: KeisukeYamashita/auto-pull-request-merge@v1
