name: Auto-merge Crowdin PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-merge:
    if: |
      github.actor == 'github-actions' &&
      startsWith(github.event.pull_request.title, 'New Crowdin translations')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Enable auto-merge for Crowdin PR
        run: |
          gh pr merge "$PR_URL" --merge --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
